zeebe:


  client:
    broker.contactPoint: 10.180.8.171:26500
    security.plaintext: true

    worker:
      hazelcast:
        connection: 10.180.8.171:5701
        connectionTimeout: PT30S

spring:

  datasource:
    url: jdbc:mysql://10.180.4.18:3306/zeebe_monitor
    username: mysql
    password: P@ssw0rd!
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  mustache:
    prefix: classpath:/templates/
    suffix: .html
    expose-request-attributes: true

  data:
    web:
      pageable:
        default-page-size: 10

server:
  port: 8082

logging:
  level:
    root: ERROR
    io.zeebe: INFO
    io.zeebe.monitor: DEBUG
    com.hazelcast: WARN